# Definition of QA pipeline at SonarSource


TEST:
  - plugin
  - ruling

SQ_VERSION: 
  - DEV
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]

exclude:
  - TEST: plugin
    SQ_VERSION: LATEST_RELEASE

  - TEST: ruling
    SQ_VERSION: DEV

  - TEST: ruling
    SQ_VERSION: LATEST_RELEASE[6.7]
