docker:
  image: yegor256/java8
architect:
- yegor256
- dmarkov
install:
- sudo gem install --no-rdoc --no-ri pdd
- sudo gem install --no-rdoc --no-ri xcop
assets:
  secring.gpg: zerocracy/home#assets/secring.gpg
  settings.xml: zerocracy/home#assets/jcabi/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  s3cfg: zerocracy/home#assets/s3cfg
merge:
  commanders:
  - carlosmiranda
  - darkled
  - dmzaytsev
  - ggajos
  - hdouss
  - krzyk
  - longtimeago
  - mkordas
  - pinaf
  script: |-
    mvn clean install -Pjcabi-github -DskipITs -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
deploy:
  script: |-
    mvn clean deploy -Pqulice -DskipITs --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=jcabi-github.xml
    s3cmd --no-progress put jcabi-github.xml --config=../s3cfg s3://pdd.teamed.io/jcabi-github.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Dinvoker.skip -DskipITs -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite -DskipITs -Dinvoker.skip --errors --settings ../settings.xml || echo 'site-deploy failed'
  commanders:
  - yegor256
