language: java
jdk:
  - oraclejdk8
env:
  global:
  - BUILD_SYSTEM=travis
  matrix:
  - SPRING_PROFILES_ACTIVE=nflow.db.h2
  - SPRING_PROFILES_ACTIVE=nflow.db.postgresql
  - SPRING_PROFILES_ACTIVE=nflow.db.mysql
addons:
  postgresql: "9.4"
before_script:
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ postgre ]]; then psql -c "create user nflow with password 'nflow';" -U postgres; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ postgre ]]; then psql -c "create database nflow owner nflow;" -U postgres; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ mysql ]]; then mysql -v -e "create database nflow character set utf8mb4;" -u root; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ mysql ]]; then mysql -v -e "create user 'nflow'@'%' identified by 'nflow';" -u root; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ mysql ]]; then mysql -v -e "create user 'nflow'@'localhost' identified by 'nflow';" -u root; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ mysql ]]; then mysql -v -e "grant all on nflow.* TO 'nflow'@'%';" -u root; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ mysql ]]; then mysql -v -e "grant all on nflow.* TO 'nflow'@'localhost';" -u root; fi
  - if [[ "$SPRING_PROFILES_ACTIVE" =~ mysql ]]; then mysql -v -e "flush privileges;" -u root; fi
after_script:
  - for i in nflow-*/target/surefire-reports/*.txt; do echo ">>>>>>>>>>>>>>>>>>>"; echo $i; echo "<<<<<<<<<<<<<<<<<<<<<"; cat $i; done
#notifications:
#  flowdock:
#    secure: QbIGfsj64a2Ms5y/aTO0PUAVBRv9mKxAwLFj5NxWACEVxm1JKZvrQ4ov/8XbVRbRl96sMIoWPox7Gu++ZgLjb7w+jeiCvWLwJwRDxlCgsYvb4hAcPXlNBO7SF4kcUifPfJpaDsb3EThUUK8EtsI5aOxvCqGKMChTDoQnej3kc0o=
#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
#cache:
#  directories:
#  - $HOME/.m2
#sudo: false

