dist: trusty
language: java
jdk:
  - openjdk8
  
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar
   
before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/com/github/dadrus/test
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

install: true

script:
  - ./build.sh
