language: java
jdk:
  - oraclejdk8

# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  only:
    - master
    
deploy:
  provider: heroku
  api_key: 525db115-ecfc-4d9e-9053-1e306e1f37f1
  app: demo1mep