language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
      - "$HOME/.m2"
      - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "portux-github"
    branches:
      - master
      - develop
    token:
      secure: "igcGgKleBOmdKd+/JoIugDC9c4aXsOy795r4M06GzELukAtO0/pf3Mv0C1jOxB4WT9XUxx6hgFqRvzHb0rpkoF/fHldm6IDIKiVqbQsIx6RQwktMvgEO6J5GB+wBrmkn0G/Wr+QFwCVHtA5ZgncFcjiZK+ajhA6eMi35bd1YfkJZ7UNNsmiIHFZoXQMPRMsCcML2alTMG4VB8KkA/+RrQcieXSNKlybaQfx43XCaH5u1bmcjl2GLFqsMR47bNeBe29Hn/+NrqDFkDwpBPsLQ7U+E4KSQqX+lxrWGtgpFYVp3UmFf6B/0z+UdOr7hj8nAMldJ9Ak7a7F41oQwh2x9Lyxk44B8lf5I6X42Xiav8KXdGWJFJnYaSpmNQaRhDq7FKQrNlZjWwWLalptpDTzXOxteiR0XTDg+YktJnKKankp7YFY3jWMJWZJDQYdanGRMD51OHYmWoRiMlHdtaOSwA9yxG1ukb2BXXcTz+Assn3AK23/HoVNaScQkT/GdZwkRv/ipb78BRUFAghq/xNf4CELgJ0za5A9TeUknXUEvop1IDWfa03elo4v53hzUW3OXmdmC6ubWI36cwb6k4uQRlVPUBv6jhYIpeJvQyVM0OrZSOl76KAkWN4irivx0fxYUkuWHkpCZDhBAD0TqlfkZt/xsBjIwhIaPEHGt8ZW3j3Y="

#notifications:
#  slack:
#    secure: O2F2K0E5t/XERfZzM8Q9ylyABpNtN+FM7PvYV32u/YzsqPDl6HLiXgSSqjcpj3OESMjkk6cFJTVNNxOd88BRFL26jeI5sIA76tKnTVrJrPNCf4MksIwvpeHRjgIA0Juz13nDlbJcvZuVIBn35Esl/NbbzMKgUQNqqUTzCiyk1OXjyD4nbnTG+aHs+Kpe5KMvBN5Pqp8HjlpxwcRkUa0RalK9v8c9e8zXgj2ZeJ0W2nLD05PtywMn77XlI3/HrhJMa3HLbniUMy8MVokfOcxcoBVL7UHHvbwX1HmwtiP8MB9XnLWmTadw8gB8p3x4iXdgZuG/e863QwQWNzoRdmG1vs/vT4/aKv8n5EdXxZPhio5vmDD9bIW1NuDxGs6Tzok8OguYkzjQ20Qpd5TplQHBlyQ+v797GW7Ix/fsI0nuiNerpOZ23lPPq67X61fdZIbaCtposMkUD0hhbQ64rHDVf4wHyqIxIu3+2hYojySTkfDOLvnjHIoS2klwbFk6u5ATEl5ONi3rJ4U8PVVmgjOC3xBCsoJVQciGccU3R2Ww3ZIVrqPV+tHT43WnBjwxh3hQ+TQJeALU/V8VnvoGMYB5TaJBlUNcXB2Bb5Z6EVC1i8OMcs2wPtW/TasDtu5bA6tcq/N/OaQHm38zz8A1fhieLlHoYXPm3D/xPBPTTYMxp3Y=
