language: java
jdk: oraclejdk8
sudo: false

addons:
  sonarcloud:
    token:
      secure: "BZHKofLWAebdg6XL7aHcJlRJ8YIjYfJdk8vlltNb9TuhRTrdFJ+bjOCMFN8iiPtg2uDNdbj13B2/TVbTwixeanrTz7zNTFo+I37kRuxtMV3qZZB7dBgjceu/xTRBX1XCNXhHpyoblBZcQntaKlLm5qnASs78GRUJr8YNFNZsTjE="

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script: mvn -Dsurefire.useFile=false test

#Remove .yamcs directory before running sonar, otherwise the XTCE Db loader will not be measured for test coverage
after_success: rm -r $HOME/.yamcs; mvn -Dsurefire.useFile=false clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
