sudo: false
language: java
#services:
#- docker

jdk:
  - oraclejdk8
  
cache:
  directories:
  - "$HOME/.cache"

#deploy:
#  provider: script
#  script: "mvn --settings .travis.settings.xml -Dmaven.test.skip=true -P ci-build deploy"
#  skip_cleanup: true
#  on:
#    tags: true