language: java
jdk:
  - oraclejdk8
sudo: required
dist: trusty
before_install:
  - git clone https://github.com/Tillerino/oppai.git
  - cd oppai
  - ./build.sh
  - sudo cp oppai /bin
  - cd ../tillerinobot

# we're not installing anything
install: true

script:
  - mvn verify -Dmaven.javadoc.skip=true -B -V
  
cache:
  directories:
    - $HOME/.m2/repository