language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
#notifications:
#  email:
#  - cse63152@gmail.com
#  on_success: always
#  on_failure: always
#script:
#- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#- mvn clean package docker:build
#- docker push huajwang/licensing-service:ttmall
#- docker push huajwang/confsvr:ttmall
#- docker push huajwang/eurekasvr:ttmall
#- docker push huajwang/organization-service:ttmall
#- docker push huajwang/zuulsvr:ttmall
#- docker push huajwang/specialroute-service:ttmall
#- docker push huajwang/authentication-service:ttmall
#env:
#  global:
#  - secure: KYjMQ+CybqP7P3uwSqpIOqio/q3PxkHbmj01W+03JPsKrKNH8KZ/U4iVstVyEKN/S64w0XP62oMQVjLSyfGgfWcscslr7etQxfye1YGlUrtCGoUIuerJvYrRtC2DsHRlOwWT+1Xmwzq4//czALVbZjYNmof0kDyGXY1+l7nAQNkLl2uJJEIpwLeSsTh1xkVzMdyHrUAGeiLHK0kJ5jvtA4fWnDOsRzfPyxo/P44Za3u571kPbS9IfNMyPKdKWZULE50xCgf8dMyYlcPjhJai7aMhBAtTE8g845KVFN5/F/8v4xu5zuKocKsIDPobuYQLpXXTt2QoNkViD2RMwaLao1y7GjKIRLXA98yiYTe2Qso0pSyOmRkvrRHYvpP/Udqi0rTISl5dzKUr4XJnzUtNWciOM5ZbAE2IADwdNhV14sKp4o5QuZbP/9unNP6pB/ONVKEdKcpcKyv83Y7shgLUtryV6ODXuRw1f1H+0xJDbwLyXwBX5uArYtEUhrpwjXDN+bvxkd2TALhAL4bnF2NhuWjSVw+5vrU2CH6e/yd/dkf9LDDJDKKYPwIDAgseDl3pT6H8litHX08/UaxsqarFpHkxi336IMwUVI6/GJQCR+AaAeIsR3ZkFDLQeQtCctWzVXZzU1xPgSw9cSYNU+x6T7bjih8k6wXYPNGussrnMKs=
#  - secure: FKyjxafww7sypWxDAOj8kIVGurdTCdRxO20cY31bFwCiJQz1PAxWo5xpjV37T5QfVDpB6d2eOjufgzG6O12++TBlLNffpVg8pmg04veXdt9tMW7vXaEJS3OyPeFJNXoUqbP6q9PQFEgJ2x51Tfzha9Oc/T/hjeYXLMFxrx6SedD9bGAcRF5acaI4X/x3naLjfSjB1Mbrrpoq+LzXa8VxZZsNl4+PHP1CJq+fRWijO+XDbvqKgWjlqEjZAf5DSFLSPjeCh2YWihgCbwC+e77IQUKgpAUbYkJPOKL3de8dBvDKf3TJRw2cv8DUvY8OEs1KDmYbWXkwsYnhqB1uu5P6/oCe/H8WMyqOkt/qroeWhPVn7DD5sWfxMN2lNv0E+NIykhZuG72LJB6KAx3sLrP86qY1WLqakKDgZpnBipVrIvZWoGaDJRWAhLHtYmxkKtMIHnr0BDovCACPYLNAWquvD2fek4baMmT78oqZw09kWIuyFC1AkXX9Q2ElMSIjceW0pi71VcZoByyJd3pCxMC/rguG646/RqUdlW7wRJDZtyRxd4Ai6G9OOQ992EZyUvIaFwU+r8GWRFZZoRrNbFgNciwbDmz5l9ouRh4s3CazPFVZfsa3JkjzTzllPMpDzt5amHBiTPiDQJzbmRtfOk9a28LCxH5nl1DZO9q9Dku50TI=
#  - secure: fVx+663KGqvnJavYh7qg7QKEttGOVo4Tl8MBzmbdGdGC34XgeeMNqUsa5E6e/hjJk6D1OLF/II7HT4Hv3JpWaTgVdzVnjawJ8w1Yrrzl/tutIWRnoi/He7mvLMcMbPqYxqMzmjE+U5r1SmPxeEDLZ34nuQjdj6y0y+LTG0WnJqVPLoXmUtLRs7F7ZKxgB35F+GqoVXuZofWl6QiL+xUc+RXeyreG7YItJ1kW+peZ4v9j1IMJzaBYhp+Fu+pjfRngUwyZrnD4Zpo577NM9BT/qwfICPi1rmWZZicXWkg3TrDMztsq4H50Ym7K+TMSGlIZlpMr85pdi/ZJdboxjcrrd3qNNwj1ICijRZdLtGCLPasjdbvYMRk8kppFBMGaqs+1dwMW1HOf72rdFg50MOATVUztFryUKEq/t/9xR1nXNq0Pip6TwEylMJeA7eGaLuuBvzAkfEZyyYQHbjdESAIvQ6RYdPBu2t0+AKBjn+DOpz227ptk2M++7Cx7yBnA7A5ovs1DmYoZ0wJM6dmkbI+oGtJlX8wJpKawNfCttQz1o8Sqj6duURZtrOgPMLgT5ufs0PTlIGTN2/lDBXm6PciwSMaMzu4wx7c+M9CFMg9lYzg2gJpbckBVx/15OWudRcIU6fspmSGuxuozrnR3uCpYTnxLSu8W2iBYY1v2x8yrVsg=
