language : java
jdk:
  - oraclejdk8
sudo: false
before_install:
  - pip install --user codecov
script:
  - mvn install -q
  - "mvn cobertura:cobertura"
after_succes:
  - bash <(curl -s https://codecov.io/bash)
