language: java
jdk: oraclejdk8

branches:
  only:
    - master
script: 
    - mvn -B verify
    - mvn deploy -s maven-settings.xml -DskipTests	-P javadoc
cache:
  directories:
    - '$HOME/.m2/repository'
