language: java
jdk:
    - oraclejdk8
script: mvn verify
after_success:
    - mvn -f core/pom.xml jacoco:report coveralls:report
install: true
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
