language: java

jdk:
  - oraclejdk8

services:
   - mongodb

script:
  - mvn cobertura:cobertura  cobertura:cobertura-integration-test test
  - bash <(curl -s https://codecov.io/bash) -t fa836755-5af2-43ae-b2b1-2062d8fe41a4