language: java
jdk:
  - oraclejdk8

before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts
  - pip install --user codecov

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov
