language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk8
  - openjdk9
  - openjdk10
# disabling since jacoco fails
#  - openjdk11
cache:
  directories:
  - $HOME/.m2
script:
  - mvn -U install -Dmaven.test.skip=true
  - mvn test
