language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: carlosthe19916
    token:
      secure: $SONAR_TOKEN
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
  -V
script:
  - mvn test -P !build-extras -B
  - sonar-scanner
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"