language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  - openjdk8
  - oraclejdk9

before_install:
  - if [ "${TRAVIS_JDK_VERSION}" == "oraclejdk7" ]; then export JAVA_HOME="/usr/lib/jvm/java-7-oracle"; export PATH="${JAVA_HOME}/bin:${PATH}"; fi
  - test "${TRAVIS_JDK_VERSION}" != "oraclejdk7" || (test ! -d "${JAVA_HOME}" && (curl http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-7u80-linux-x64.tar.gz | sudo tar xz -C /usr/lib/jvm; sudo mv /usr/lib/jvm/jdk1.7.0_80 "${JAVA_HOME}"))

script:
  - java -version
  - mvn -q verify
