
sudo: required
language: java

jdk:
  - oraclejdk8
  - openjdk7



script:
  - mvn clean cobertura:cobertura -Dtest=SlangImplTest#testSubscribeOnAllEventsWithListener -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/cloud-slang/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "K8fhvsvjlTCu9xXnErBIW93Yo1hurIu4lNToREU6V1XdLnmeyqd/O8/QkFteDdBOAyF6rpkes4CX3xt+YRuFNLtEY72SiBjz9RT24RkYxnwmn8ynEbUYwPMg6v2OtbYPwQ2dfLx+uoPF4kmRTJBGh3oIdny1/3JfWhUJRtjS1IFB+yVZX3Jp2U/XMjqfN4FjhhYdIIXNb8IRc+vuoOsE8yd2e1j29Zz3oC8M+a2pzeCkVo7A3KR6ZDdGiXUYTi7ChkEB9Innd/fTA9WIuYJhpvu32sbXfJ+lXklzNLhRTXSkMjSFHIXnkF3bL3oPWjCmszPEYIPa4zvM4Yox/tApwKkGbQcD0qfdj3RN6XG2PBsRYk7v8lH1Kk/sJmqRxWJRwOivZMjU3eYAmgv/uwTud1bJXG/prfRLUas+p+jPtyAI0B5bBodN+6jRMy8W76nHlv4dIPrwO4ZbYvRNdn8RmgCPqpTElYIcaKzislS81mMSymBxl3PrB9q8gkc4LTnGi+2cb8G4ph8lKANpskmTBivz89ezBniTrTPrEF5TVJceTGOwco9nUYgjIJQg1/orJEFuxQQymc6aWfR4ZH5m+FkudauZkdbY+IAXuADoXNhP0x+cMWFIwZRHT9Ag3n2lQrAUZkD3I5n+OkcusHEpJzxNKdBnhB9uE23NqlpeDvg="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
