language: java
install: mvn --version
sudo: false
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  app: fbob
  api_key:
    secure: aSHyeWfTVAuT/xTptu0Cw8G6boPlA02KoEWX3ZUjLap9H7TuGdjNqfXxHE2OJ02KnTReMECGyHyPOyTrGqBjgj2jwHmiOt9aol5wLndrSvvby6YfOiX8LQai53TzN9iuajlRw4+0Rbv54Jwv2uZwAp6sb16W/DG5fYUF8h/NnRIRkA1qfAbnW2pk8CNt2pMq+kTmL+vTg2bjkZl1/mj/Znomf7fhmYPAYIixlgvtWpP3EziP3qo/4nmGbD7p2Z27Nn3UekzFj8d8juvIvo9bkBBSXvomBRp+fit7sXGocYQ7+dkOkmTBK37GD4wO77iOMCkXcq6B4Im5F5dJRsM+c5nl3aLbzxcc4FBFbgvUNVJ+4Bcuqf5ro709pXvr30JYkD3GaFqEAbigegKqkk7//HRzItQdronQtL1Xj3M+ROdwpHpvaZRdd7C07JHyuBu8ERgcLHy/JaruUQ1MMAfazi1YesDstKKerblt8Zz3snV22Ur33Z5Jouqa+jvvbzzaRCxFF9b9u/u71lyq5Zx+pOrGOMFI8T4z140fRAI6s3Hz4hojnhz3xtkr3onw+3mvo6YOH3k5eR3rzIsxftWfhDNnosVhYFb3MFk9UqEoP1nXNbdcdibNYRH6rtO3iXqGzAzaBJEfoN94hslJsPZcVFDttN0u7BwFsompegnBsOo=
