language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "Er93Pupm41cnkryzKmu1q7HM7RtoT1WAjTKdx9eT8GeEsyq2b3E3QixEUGi2JwBup/O0GMLR3gY2THmE7zzBVKWPSZ7xHZLfrSADIXfvuZ
JlW5IMqsd0DCgNyNklGNkckDbq1xqWWqsb8FUzXeRFYJvkLAMriLKH+4fGg+3imWShXE0jXTMB7yemEcpCL0XJWPicLrcSqJcob8GDr1bPkCO9z4v/AbZ
/hBnf4ITSza2gDxljDqy5GPQXyT1JrEapZn0OXiLoSbaYlXjvkrndydgCIKN5H8gFW9P2Y6AnPTK6WQ7oyaaZQ+wCRoTSXK6Cw/FzvxfSBB1a5OEWR7pP
hhF7nJ9I6LdSt6eNfLQYsa74EQGYhmEkfhp6QqIumeOa2zpmgc+qajDgM53ow2zQH0zEjGL8rA08wpl1Wrvb+yk+x8abku1U9z/74xxRZyY822TNLsUPv
e4r3HfEmZMnQK3GWqIEH2EMgVeIWt0pXGaUAugfTAl3hd9Fz7SOsf+CrIEjIbGDXw1oZMGAb0mDqX55GVMZvWEg4zDQg7VShuNbugUUDHtWA9AIOLpyuV
+Wccou61hWRveaPY3Z335w8Rl0WFys6+j10nUTNifWBnLKAHer9298mbMGLgHSqpRyl4oBcO0hPcXpyljJ5SpHDxhGRTxxFeSJUR7qNkKEEtg="
   
jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  -  mvn test -B -P coverage
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  - bash <(curl -s https://codecov.io/bash)
