language: java
jdk:
- oraclejdk8
before_install: 
  git clone -b travis `git config --get remote.origin.url` target/travis
install:
  echo 'Skipping install step for Maven project'
script: 
  mvn clean -Dmaven.javadoc.skip=true source:jar deploy --settings target/travis/settings.xml
branches:
  except:
    - travis
cache:
  directories:
    - '$HOME/.m2/repository'
env:
  global:
    - secure: "u+xtj7tnEX3VNwmkV5YUEZjf9RxL3HrTCAxIyHnwqOKJSVOxHkKkG0NSnmIs9JzBlb0J3Eq6RG1a9oBXWnT8CAvIdqDQWhCjFKoD72KvkXqCVNMrR6Egt0fkVmVj+ZU/LOX95K2GlHfKOqBxxkjh/3+/G1MN9tNLakhLRrPuSqhkQxYF22Y0sgMZKSwr3EYjrHFtPPjey00IeIN12UCxlIPVWAsNMkKOxG7sqqmgNC8Ro/3o2AaGwglLfTlUdBQ4d40VvPrAUk+rvv0kr82L02H6tqPGVgeqiuYyELDdG81e7T+WpLViYKEddEdsb2ghaxwv+zzzuykqnGQqwfP3ozrP5+pbKfFdDxSjyAW1DxJkauOgC+P/ynTMtDkdM5A0JhDatyePA8Ju2Fex7vcafmF6s8xX9qrHAsTU4kxY/Qpzb8F5LnxMglA6JhbmQuScd1MMWe7RrwcZa9O7F2HfiPOwI5F13i21uahdaEzsOmDWPJxtL4/chcezjFBbvG9wPMJsaLh/aJG6SHRG2ArzmKb1s/A0kQvrvGQFDigb1X4tCObFyGgjiHFBPd+qDTbDXEY3yFqrGyjj7/OyRhmu+unTYkur7+EhBmBHnlfFNZHGp4dwCjTpu28U9HQuWrwwH48a6YT6OcJrMA/ePHPHqSMwSISsJcXa7MXEqj86cf0="
    - secure: "LxU4ZCbJzftQC64QBLxFYgx7CSAG+E7TkfbAB6OqL9SYZ1SgAaywGtQKXDCU/O/6AKkgar4PXLUXrbgaOmVmp+Xb5dI1aGGPBA19XG3LqGOZS9QV2jwYgb5qcvcPq3YD4pn95GvhjothXNerVfcT01vJoSyIBlGJBr7Ec3FMhyfwVq7ORaF4WO7JZ13d4jcRUxgI5IGc3A8wwz4XG2RRa4kZ94fcHHYpBM6PigTfnkER8DUVmEswflr1bKCSNmG0U03uWDnlnYT0vuTD0XZVp8ffeBYFeiDy1iu9n1EjhlnaboetQDBxEkFDzBeSHHsh3+tXxom15Qh2h0itOP48WMHIdj/5OmfSv6sc4BFUXi+xZ/ol3kPT4sv/OECH0D5giDqrMeC98Gk/MSv9yRy/aJRf2ZWOfKMJ+qnM2vixMe9uZ/gwGKZXG9x5NN5nwyKBLT5wFaQoHgpQO8hwAIQ5iIYInL0ofPgf9RteZYPWaTswT+MKoCPyV1H9R6pO58FpbZh+JnEI1f/xbW9njpeCIs8GL+Qd/sUPQ205Ls3eD8Qa3aqObm3DVNbMyHSaj9yoE0pVdDloGmToc9vXn+6iBsmUly8mgBL7SybKeZSqc/Mt9f1qyZvdy3ozEAgbWVF73uGuAzskmTyfh+5A4wHpu1fALZLnAUuneTbCxrV/STA="
