language: java

addons:
  sonarcloud:
    organization: "julienpinteaux-github"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar  -Dsonar.organization=julienpinteaux-github  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.projectKey=java.java340  -Dsonar.branch=master