language: java

sudo: false

jdk:
  - oraclejdk8

stages:
  - Verify
  - Install
  - Test

jobs:
  include:
    - stage: Verify
      script: mvn clean verify
    - stage: Install
      script: mvn clean install
    - stage: Test
      script: mvn cobertura:cobertura

matrix:
  fast_finish: true

after_success:
  - bash <(curl -s https://codecov.io/bash)