language: java
before_install:
- chmod +x .travis/push.sh
after_success:
- ".travis/push.sh"
env:
  global:
    secure: BeLz/gOci1auLqAN7abSR45R+ue0u7A6aCB46JH4QpzQHRtceh1ci7A22dqCQ5oSOxgSY+KtlIsj9ExK17eMzevM6zk83lIunJIoOo5IHVqmTPwdOTRQXzk6U0EVQzRxHbVsbo3eZf00FyfjI7CTiTN9sotjtqLIzFzDAsLttckUPYN1fJvVsPJyc4o0/nOQOZNMlwFJaj6cheESSSrGu7giQbFcJEw72tRtXsRWlx4Qg4FS55HXkaii4Z0hbATP0NSJLYgZmHzro5qXw4vdxgYh4t/f5TO4gvJbtBgoXgx+M8fmr1qPpJO5MAU2S2PiN8tVe+QqxLZ92YPZZxmSA46uNJohmULawGsCD/7yJF6QvTIQ3s6w/kSLYDZ0NzTdyL2f8Fiv/UOapRDht+GQIx0F09D5FZTGaolCP4hIJhpKRkKtaU2Up896qtiiMaVb/KAFximnxVtiWd+QFLkxGabLaFhYelH1YDayhUqpOXMAg+wBhLRQ5meX5jZJIuvJxUoLx5RWw+Odv1ePexYn489mCn5VcQ6h3rvEaBFpIP8Ty13SxaFOnn9BvfQSzzO9udj1MDn7NOrxqRE+eCrnfybKjo1uxhX5ubxuqc/NsWqHvtYBd27fLborhFfhwF4FBDKF6P2d7cMxPXcY5uj0m60uHqApYULgwgk1KR6UhF0=