language: java

sudo: false

jdk:
  - oraclejdk8

stages:
  - Checkstyle
  - Validate
  - Compile
  - Test
  - Verify
  - Install

jobs:
  include:
    - stage: Checkstyle
      script: mvn checkstyle:checkstyle
    - stage: Validate
      script: mvn clean validate
    - stage: Compile
      script: mvn clean compile
    - stage: Test
      script: mvn cobertura:cobertura
    - stage: Verify
      script: mvn verify
    - stage: Install
      script: mvn install

matrix:
  fast_finish: true

after_success:
  - bash <(curl -s https://codecov.io/bash)