
sudo: required
language: java

jdk:
  - oraclejdk8
  - openjdk7



script:
  - mvn clean cobertura:cobertura -Dtest=SlangImplTest#testSubscribeOnAllEventsWithListener -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/cloud-slang/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "EJcWsN71Zwd/ItxY4tgLaoST3ZxuiiFGsiC3PgG53lVmQwBkajAXcGWo8nxVt+poNz07RJqiqJgaCFv6qzoOyRwWYRmnktt70Vf3GgSfj6TPdBrCudQXDTgZpGpwZ8GeLxXZEAK5muipViP30hd+QOovm8H3gDZx2hFPILSbvnWaaCtRAkNqEm22TLDeXAeuQrh6ZZv25EF0rUaSDqCaIQzaoN3XJ6sXa5wbc+tFiVXd13fJXQZopP+Bk900Ce40JqHQvNoLEImdmVquzxyAZeIrsqqpBE27Q6sgND3K0fPlmXir7tVYCwhaN4sxW3FBA0HM1R7960t5EV3Z+/Oknj5catAJoYz5Z/KnNCIHmr2sR7coKdm5uhyEVXCKnSzVAVABWeYdLZxNnqOwqTNos2erg+16meWyuDotlK22tQTD7t86V0wxKcJo12IH54quJdJO6/qhUyaS0aIhR/fhdjQD0ohwW5J5lgJjTZrKz3HLvtEnH90KAwUrFEa+8OOQKIMbqdcynIJk22eU/HxVHS70qxz/4ip5iqxK2MPcXwPeLLXuq7X1yNjt7lvq/dmxwI2OCVgr3E/BjBtFvrxiJDH251VWf/FLokERkwBNi49KtTcD7IdbseSgQLV+GThVXONchBSk8mYunPV1EuK8h3RELO3TCsvNQZp/oMycX7c="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
