dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
script:
  - ./mvnw clean install -B
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app:
    master: radiant-plateau-74961
  on:
    branch: master