language: java 

sudo: false

cache:
  directories:
  - $HOME/.m2
  
before_script: "mvn cobertura:cobertura"

jobs:
  include:
    - stage: build
      script: mvn clean install
    - # stage name not required, will continue to use `test`
      # script: ./test 2
    - stage: test
      script: mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
