language: java
sudo: false

jdk:
  - oraclejdk8
# failing with [cobertura-maven-plugin: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/java-9-oracle/../lib/tools.jar  so just disabling for now.
#  - oraclejdk9    
#  - openjdk8

#script: "mvn cobertura:cobertura"
#
after_success:
  - bash <(curl -s https://codecov.io/bash)
