language: java

sudo: false

env:
  global:
    - BASEURL=https://archive.apache.org/dist/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.zip
    - FILE=apache-maven-VERSION-bin.zip
    - DIR=apache-maven-VERSION
    - VERSION=3.5.3
    - secure: "NJ1w0QJMpWHDz37+f6V1vZ2on7dDVxIup7jtjlvxI192l/ETjEHop2DHJp7HEjZ6ZcC9ZJAClSW0ew7az4GaaHxvFMb2xkxH7weOPE+REZM7xHGjkYI1ElKj87d68idUT6N0kzYmN5k1wOhCvMiIUPSUMia83TfTl4USAGOVKPs="
    - secure: "kwD93y0KiVmGHvefffVn7Hd7T1ZeZh+4E41LqXBAYxYGFCSYXrPlNygO6dxjKgfSSSPXqXu9SgNXdEwZez/qoIA+TAm3VOsKVcKaIJ/0En2hmUp/yLmQa3Rc9rkDdCodDkYumD6650I0l2s17w5YATVTeoUfgyAbGZLRLlmKrmY="
    - secure: "hNjTA8dataGmylZo0QY4uhx8BNKQfJzfwdMMO7EdbfpEyqj9K7lIDIpcU/vCDgzUF+nISY0iaxr0ErguFYIat5VWM/4tKwQjfK+2MFNjzLlBsAVWirIsLoASzSIUroWKVUwSg61qTmuEf5A+aKhxNrvWALXaHgCoPU8DOpE2P6s="

before_install:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
         wget --no-check-certificate $(echo -n $BASEURL | sed -e 's#VERSION#'$VERSION'#g');
         unzip -qq $(echo -n $FILE | sed -e 's#VERSION#'$VERSION'#');
         export M2_HOME=$PWD/$(echo -n $DIR | sed -e 's#VERSION#'$VERSION'#');
         export PATH=$M2_HOME/bin:$PATH;
     fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
         brew update --quiet;
     fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$JVM" == "latest" ]; then
         brew tap caskroom/cask;
         brew install Caskroom/cask/java;
     fi
   #- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$JVM" == "latest" ]; then
   #      sudo apt-get update -qq;
   #      sudo /bin/echo -e oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections;
   #      sudo apt-get -o Dpkg::Options::="--force-confnew" install -y oracle-java9-installer oracle-java9-set-default oracle-java9-unlimited-jce-policy;
   #      sudo update-java-alternatives -s java-9-oracle;
   #  fi
   - echo $TRAVIS_OS_NAME
   - echo $JAVA_HOME
   - echo $TRAVIS_JDK_VERSION
   - echo $VERSION
   - echo $M2_HOME
   - java -XshowSettings:vm -version

install:
  # install without any testing to get dependencies in place
  - mvn install -Dmaven.test.skip=true -B -V -fae

script:
  - unset GEM_PATH
  # execute unit and integration tests
  - mvn -e -fae -B -DWatchMojoTestSleeptime=90000 -Dfailsafe.useFile=false clean test verify -Dtest="*,!WatchMojoTest" -Dorg.slf4j.simpleLogger.showDateTime=true
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ] && [ "$VERSION" == "3.5.3" ]; then
         mvn javadoc:javadoc;
         mvn javadoc:test-javadoc;
    fi

after_success:
  # generate code coverage report, just for oraclejdk8 and latest maven
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.5.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn -B -e -fae -Ptravis-ci clean verify jacoco:report coveralls:report;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.5.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ] &&
       [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
         echo "Attempt to deploy snapshot artifact";
         travis_wait mvn deploy --settings .travis/settings.xml -DskipTests=true -B;
    else
        echo "Not deploying snapshot artifact";
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$VERSION" == "3.5.3" ] &&
       [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ] &&
       [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
          echo "Attempt to deploy maven site";
          travis_wait mvn -e -fae -B site-deploy --settings .travis/settings.xml;
    else
          echo -n "not deploying maven site";
    fi

os:
  - linux
  - osx

matrix:
  fast_finish: false
  include:
    # additional builds
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk8
      env: VERSION=3.2.5
    - os: linux
      jdk: oraclejdk8
      env: VERSION=3.3.9
    - os: linux
      jdk: oraclejdk8
      env: VERSION=3.5.0
 # skip this as it is the current travis-ci linux setup
 #   - os: linux
 #     jdk: oraclejdk8
 #     env: VERSION=3.5.2
    - os: linux
      jdk: oraclejdk8
      env: VERSION=3.5.3
    - os: linux
      jdk: oraclejdk8
      env: VERSION=3.5.4
    - os: linux
      jdk: oraclejdk9
    - os: osx
      env: JVM=latest
# skip this as it is the current travis-ci osx setup
#    - os: osx
#      env: JAVA_HOME=/usr/libexec/java_home
  allow_failures:
#   - env: JVM=latest
#   - jdk: oraclejdk9


cache:
  brew: true
  directories:
  - $HOME/.m2
  #- /Library/Caches/Homebrew
