language: java
sudo: false

jdk:
  - oraclejdk8
git:
  submodules: false
install: true
script: ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

before_cache:
  # remove all the artifacts that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/python
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'

#notifications:
#  email: false
#  webhooks:
#    - secure: "kY/6qPf7wxMrEhC+ch4XTChAukoIUw0RG3IK7vRY9ATSI9vTF3XNpXu6c53CwhnDcdDacaTIYVxrw+ewpIr0AWd3Pvtixb2X7Z/nzN2PdetvL7bqzXsTwfss7YlWOIHO+pt54cb8lRbVnp9uNxINBMGPpjLK1h+Szb+YJThp6e0="
