language: java
sudo: required
services:
 - docker
jdk:
  oraclejdk8
script:
  - ./mvnw clean install
before_deploy:
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  skip_cleanup: true
  provider: script
  script: ./mvnw deploy -DskipTests -Pdocker
  on:
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
