language: java

#notifications:
#  email: false


jdk:
  - oraclejdk8

script: mvn test -B -fae

#before_install:
#  -   mvn install:install-file -Dfile=sb-nexus/mg4j-1.0.1.jar -DpomFile=sb-nexus/mg4j-1.0.1.pom
#  -   mvn install:install-file -Dfile=sb-nexus/je-3.3.82.jar -DpomFile=sb-nexus/je-3.3.82.pom
#  -   mvn install:install-file -Dfile=sb-nexus/wayback-core-1.8.0-20130411.jar -DpomFile=sb-nexus/wayback-core-1.8.0-20130411.pom
#  -   mvn install:install-file -Dfile=sb-nexus/ia-web-commons-1.0-20130411.jar -DpomFile=sb-nexus/ia-web-commons-1.0-20130411.pom
#  -   mvn install:install-file -Dfile=sb-nexus/heritrix-1.14.4.jar -DpomFile=sb-nexus/heritrix-1.14.4.pom

