version: '3'
services:
  eurekaserver:
    image:   huajwang/eurekasvr:ttmall
    ports:
      - "8761:8761"
  configserver:
    image: huajwang/confsvr:ttmall
    ports:
       - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  authenticationservice:
      image: huajwang/authentication-service:ttmall
      ports:
        - "9999:9999"
      environment:
        PROFILE: "${PROFILE_ACTIVE}"
        SERVER_PORT: "9999"
        DATABASE_PORT:     "3306"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        ENCRYPT_KEY: "IMSYMMETRIC"
  ui:
    image: huajwang/ui:ttmall
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "3306"
      CONFIGSERVER_PORT:        "8888"
  licensingservice:
    image: huajwang/licensing-service:ttmall
    ports:
      - "8282:8282"
    environment:
      PROFILE: "${PROFILE_ACTIVE}"
      SERVER_PORT: "8282"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "3306"
      CONFIGSERVER_URI: "http://configserver:8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
    image: huajwang/organization-service:ttmall
    ports:
      - "8181:8181"
    environment:
      PROFILE: "${PROFILE_ACTIVE}"
      SERVER_PORT: "8181"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "3306"
      CONFIGSERVER_URI: "http://configserver:8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroute-service:
    image: huajwang/specialroute-service:ttmall
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "3306"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY: "IMSYMMETRIC"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092 
    
