server:
  servlet:
    context-path: /uaa
  port: 9999
  
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.longmaple: DEBUG
    
spring:
  security:
    user:
      password: password