spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect

---

spring:
  profiles: dev
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
          hibernate:
            temp:
              use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://p2.cgvagyrktgj5.us-east-1.rds.amazonaws.com:5432/p2
    username: p2
    password: dudedudedudedude
    platform: postgres
    driver-class-name: org.postgresql.Driver
    jackson:
      serialization:
        write_dates_as_timestamps: false