endpoints:
  default:
    web:
      enabled: true

management:
  endpoint:
    info:
      enabled: true
    beans:
      enabled: true

spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    generate-ddl: true
    show-sql: true

hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: "/var/lucene/indexes"