cleanstone:
  subServer: false

  mainServerAddress: 127.0.0.1
  mainServerPort: 25564

  requiredSubServers:
   - 127.0.0.2

  port: 25564
  address: 0.0.0.0

minecraft:
  port: 25565
  address: 0.0.0.0
  mcpePort: 19132
  mcpeAddress: 0.0.0.0
  onlineMode: true
  motd: Cleanstone Advanced Minecraft Server
  maxPlayers: 10000
  autoLoadWorlds:
  - world
  - world_nether
  - world_the_end
  firstSpawnWorld: world
  ops:
  - fionera
  - MyzelYam
  - succcubbus
  maxViewDistance: 32

logging.level.org.springframework: warn
logging.level.com.whirvis.jraknet: warn
logging.level.rocks.cleanstone: debug