spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers: localhost

server:
  port: 9001
  
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.longmaple: DEBUG
    
example.property: "I AM IN THE DEFAULT - directly from project config "

redis:
  server: redis
  port: 6379
