---
# tasks file for webdrivers
- name: WEBDRIVERS | delete webdriver folder executables
  file:
    path: "{{ webdriver_folder }}"
    state: absent

- name: WEBDRIVERS | create webdriver folder
  file:
    path: "{{ webdriver_folder }}"
    state: directory

- name: WEBDRIVERS | Download geckodriver for firefox
  get_url:
    url: "https://github.com/mozilla/geckodriver/releases/download/v{{ geckodriver_version }}/geckodriver-v{{ geckodriver_version }}-linux64.tar.gz"
    dest: "{{ webdriver_folder }}"

- name: WEBDRIVERS | Extract geckodriver archive
  unarchive:
    src: "{{ webdriver_folder }}/geckodriver-v{{ geckodriver_version }}-linux64.tar.gz"
    dest: "{{ webdriver_folder }}"

- name: WEBDRIVERS | Download chromedriver for chrome
  get_url:
    url: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"
    dest: "{{ webdriver_folder }}"

- name: WEBDRIVERS | Extract chromedriver archive
  unarchive:
    src: "{{ webdriver_folder }}/chromedriver_linux64.zip"
    dest: "{{ webdriver_folder }}"

- name: WEBDRIVERS | Copy webdrivers to /usr/bin
  shell: 'cp {{ webdriver_folder }}/* /usr/bin/'

- name: WEBDRIVERS | run Xvfb
  shell: 'Xvfb :10 -ac &'
