apiVersion: v1
kind: ClusterRole
metadata:
  labels:
    app: enmasse
  name: enmasse.io:address-space-controller
rules:
  - apiGroups: [ "", "project.openshift.io" ]
    resources: [ "projectrequests" ]
    verbs: [ "create" ]
