version: '2'

services:

  graphite:
    image: "graphiteapp/graphite-statsd:latest"
    ports:
      - "80:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always
    networks:
      - hesperides-network

networks:

  hesperides-network:
    driver: bridge
