apiVersion: v1
kind: ClusterRole
metadata:
  name: enmasse-admin
rules:
- apiGroups:
  - user.openshift.io
  - ''
  resources:
  - users
  verbs:
  - get
- apiGroups:
  - project.openshift.io
  - ''
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - ''
  - user.openshift.io
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
