apiVersion: v1
kind: Template
objects:
- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.enmasse.io
  spec:
    group: enmasse.io
    groupPriorityMinimum: 1000
    insecureSkipTLSVerify: true
    service:
      name: api-server
      namespace: ${ENMASSE_NAMESPACE}
    version: v1
    versionPriority: 15
parameters:
- description: Namespace where EnMasse is running
  name: ENMASSE_NAMESPACE
  value: enmasse
