server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/huajwang/config-repo/
          searchPaths:  > 
                licensingservice,organizationservice,
                messageservice,specialrouteservice,authenticationservice,address,
                goodservice
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/